
Here's a very simple GitHub Actions workflow that just checks out your code and echoes "Hello World" when code is pushed to the main branch:

yaml
Copy code
name: Simple Workflow

# Run workflow on any push to the main branch
on:
  push:
    branches:
      - main

jobs:
  simple-job:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run a simple script
        run: echo "Hello World!"
